name: Benchmark

on:
  pull_request:
    branches: [main]
    paths-ignore:
      - '**/*.md'

  push:
    branches: [main]
    paths-ignore:
      - '**/*.md'

  merge_group:

  workflow_dispatch:

jobs:
  benchmark:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    env:
      PUPPETEER_SKIP_DOWNLOAD: 'true'
      PUPPETEER_EXECUTABLE_PATH: '/Applications/Google Chrome for Testing.app/Contents/MacOS/Google Chrome for Testing'
    strategy:
      fail-fast: false
      matrix:
        os: [macos-15]
        case: [react-1k, react-5k, react-10k, ui-components, popular-libs]

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          fetch-depth: 1

      - name: Install Pnpm
        run: |
          npm i -g corepack@latest -g --force && corepack enable
          pnpm -v

      - name: Setup Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7
        with:
          node-version: 24.21.0

      - name: Install Global Dependencies
        run: |
          npm i cross-env -g

      - name: Install Dependencies
        run: pnpm install

      - name: Run Benchmark
        run: cross-env CASE=${{ matrix.case }} pnpm benchmark
